### ISSUE TITLE
An initial website need to be setup

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO_website#1]
An initial website need to be setup.

The website 
- is basically static except of (if required) some jquery codes.
- informs what Robotframework AIO is,  
- provides download links for our releases
- provides links for our repositories (if somebody want to use repositories independently of RobotFramework AIO) 
- provides links to github for issues
- language shall be english

**Comment by HolQue** [comment]
* defines a short name for browser bookmarks

**Comment by ngoan1608** [comment]
Hi @test-fullautomation,
Hi @HolQue,

Please refer the initial webpage for our RobotFramework AIO.
Preview version: https://htmlpreview.github.io/?https://github.com/test-fullautomation/RobotFramework_AIO_website/blob/ntd1hc/feat/an-initial-website-need-to-be-setup/index.html

I have just defined the template of website and which information will be described within these sections.
Currently, there is no icon for RobotFramework AIO (We need to design it), so I use the Robotframework icon temporarily.

Please give your idea about:
- structure of the content
- key information within each section
- styles: such as background (if requires), color, ...

Then, I can proceed to give more information/explanation/image for content.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,

please proceed like this. It's a very good starting point.
The chapters should be loaded  from separate HTML documents, but I think that's anyhow clear...
Background (picture) we don't need, but we should find a color which stands for RobotFramework AIO. 
Can you try RGB:40, 10, 100 for the navigation bar.

Documentation will be searchable HTML as per a proposal from Holger.

I found that in mobile mode the button has no function...
![grafik](https://user-images.githubusercontent.com/73528834/215450902-7fd91861-5371-4ac3-925e-95ddafe44b10.png)

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi @test-fullautomation ,

I have temporarily hosted this website at this http://hc1-v-0002y.hc.apac.bosch.com/
I have added the [icon for our RobotFramework AIO](https://raw.githubusercontent.com/test-fullautomation/RobotFramework_AIO_website/ntd1hc/feat/an-initial-website-need-to-be-setup/images/RobotFramework_AIO.ico). My initial idea is just the RobotFramework icon inside the gear but then I changed it bases on my idea that our automation package contains Python, RobotFramework, VSCodium and they works together.
Some images/gif for the feature, usage sections are also added.
Please give your idea about them.

The other sections from **Document** are under developing.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Cool, cool, cool. I am so much impressed!

**Comment by test-fullautomation** [comment]
Hi Ngoan,
very good, also the icon proposal is good!

Just some ideas:
* In the introduction we need links to robotframework core, vscodium and python39.

* It is not only easier to get started, it includes e.g. a process for version control, that everybody uses the allowed bundle(s), which is important for production test and test result reliability.

* We need links to all our libraries with a short descriptions what it is for with a link to the repo and PDF (both in a new window).

* search you can hide at for the first version.

* any idea where we put the installers? github is only visible when you are logged in. Without login you can't access the images if I'm not wrong.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
WebSite is online.
http://www.robotframework-aio.org
